
export const userPosts = [
    {
    id: 1,
    postImageUrl: '../../../../../../assets/images/puppy.png',
    userID: 1,
    loggedInUserID: 15,
    loggedInUserImageURL: '../../../../../../assets/images/ProfileImage1.png',
    userFullName: 'Chandler Bing',
    userImageURL: '../../../../../../assets/images/profile-7.png',
    postDate: new Date(),
    postTotalLikes: 66,
    postTotalComments: 30,
    postTotalShares : 4,
    postComments: [
        {userID: 11,
            userFullName: 'John',
            userComment: 'Lorem ipsum dolor sit amet consectetur.',
            commentDate: new Date(),
            userImageURL: '../../../../../../assets/images/profile-2.png',
            liked: false
        },
        {userID: 12,
            userFullName: 'John',
            userComment: 'Lorem ipsum dolor sit amet consectetur Lorem ipsum dolor sit amet consectetur.',
            commentDate: new Date(),
            userImageURL: '../../../../../../assets/images/profile-2.png',
            liked: true,
        },
        {userID: 13,
            userFullName: 'John',
            userComment: 'Lorem ipsum dolor sit amet consectetur.',
            commentDate: new Date(),
            userImageURL: '../../../../../../assets/images/profile-2.png',
            liked: false,
        },
    ]
     },
     {id: 2,
        postImageUrl: '../../../../../../assets/images/bull.png',
        userID: 2,
        userFullName: 'Monica Geller',
        userImageURL: '../../../../../../assets/images/profile5.png',
        postDate: new Date(),
        postTotalLikes: 90,
        postTotalComments: 20,
        postTotalShares : 4,
        loggedInUserID: 15,
        loggedInUserImageURL: '../../../../../../assets/images/ProfileImage1.png',
        postComments: [
            {userID: 7,
                userFullName: 'John',
                userComment: 'Lorem ipsum dolor sit amet consectetur.',
                commentDate: new Date(),
                userImageURL: '../../../../../../assets/images/profile-2.png',
                liked: true,
            },
            {userID: 8,
                userFullName: 'John',
                userComment: 'Lorem ipsum dolor sit amet consectetur Lorem ipsum dolor sit amet consectetur.',
                commentDate: new Date(),
                userImageURL: '../../../../../../assets/images/profile-2.png',
                liked: false,
            },
            {userID: 9,
                userFullName: 'John',
                userComment: 'Lorem ipsum dolor sit amet consectetur.',
                commentDate: new Date(),
                userImageURL: '../../../../../../assets/images/profile-2.png',
                liked: false,
            },
        ]
         },
         {id: 3,
            postImageUrl: '../../../../../../assets/images/puppy.png',
            userID: 3,
            userFullName: 'Rachel Green',
            userImageURL: '../../../../../../assets/images/profile5.png',
            postDate: new Date(),
            postTotalLikes: 100,
            postTotalComments: 40,
            postTotalShares : 4,
            loggedInUserID: 15,
            loggedInUserImageURL: '../../../../../../assets/images/ProfileImage1.png',
            postComments: [
                {userID: 20,
                    userFullName: 'John',
                    userComment: 'Lorem ipsum dolor sit amet consectetur.',
                    commentDate: new Date(),
                    userImageURL: '../../../../../../assets/images/profile-2.png',
                    liked: false,
                },
                {userID: 21,
                    userFullName: 'John',
                    userComment: 'Lorem ipsum dolor sit amet consectetur Lorem ipsum dolor sit amet consectetur.',
                    commentDate: new Date(),
                    userImageURL: '../../../../../../assets/images/profile-2.png',
                    liked: false,
                },
                {userID: 22,
                    userFullName: 'John',
                    userComment: 'Lorem ipsum dolor sit amet consectetur.',
                    commentDate: new Date(),
                    userImageURL: '../../../../../../assets/images/profile-2.png',
                    liked: false,
                },
            ]
             }
]
